name: BackyardSaturdays
favicon: null
layout_spectrum: 0.91767
typography_spectrum: 0.619895315496251
title: Backyard Saterdays
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74200105-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eefbc3'
    - '#505568'
    - '#232428'
    - '#a3a3ab'
    - '#5077fa'
  brandStrength: 0.375
  lightness: 0.6159274510573596
  saturation: 0.8273821440525353
  rhythmicContrast: 0.75
purpose: []
