name: BackyardSaterdays
favicon: null
layout_spectrum: 0.5339879903476685
typography_spectrum: 0.619895315496251
title: Backyard Saterdays
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3678996367380023
  lightness: 0.6159274510573596
  saturation: 0.8273821440525353
  rhythmicContrast: 0.8374872277490795
purpose: []
